### ISSUE TITLE
bug: telescope and other popups have annoying light background when transparency is off

### ISSUE THREAD

**Issue by andviro** [0xstepit/flow.nvim#10]
### Did you check docs and existing issues?

- [X] I have read all the flow.nvim docs
- [X] I have searched the existing issues of flow.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Linux, alacritty.

### Describe the bug

Hi there! Thanks for very eye-friendly colorscheme, it just clicks with my tired eyes. But the decision to use gray6 as a background for floats and popups like telescope is somewhat questionable. I'm sure that I'm doing something wrong, but it looks now like that:
![image](https://github.com/user-attachments/assets/3d4ecb98-ccbe-457c-ba8f-4c9d6b61ea3d)

### Steps To Reproduce

Just switch on the color theme and bring up telescope

### Expected Behavior

I think it would be nice to keep float backgrounds to default background color or at least add an option to do just that.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "0xstepit/flow.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("flow")
-- add anything else here
```

**Comment by 0xstepit** [comment]
Hey @andviro, thanks for opening the issue! I'll work on it in the coming days, but feel free to submit any color scheme PRs in the meantime—they're more than welcome! :)

**Comment by 0xstepit** [comment]
Hey @andviro, the PR should fix the issue. Thanks again for reporting it! I always use a transparent background so I didn't notice the bug :)
