### ISSUE TITLE
bug: Extras files generation fails due to missing global vim

### ISSUE THREAD

**Issue by ctffarley** [0xstepit/flow.nvim#14]
### Did you check docs and existing issues?

- [X] I have read all the flow.nvim docs
- [X] I have searched the existing issues of flow.nvim

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

MacOS 14.2.1

### Describe the bug

Extras generation fails with  `lua: ../../flow/colors.lua:61: attempt to index a nil value (global 'vim')`

### Steps To Reproduce

1. Run `lua main.lua -v` in the `/lua/flow/extra` folder

### Expected Behavior

The extra files would be generated without error. I was able to work around this by commenting out the `if` block from lines 61 to 64.

**Comment by 0xstepit** [comment]
Hey @ctffarley, thanks for opening the issue! The bug is now fixed :)
