### ISSUE TITLE
bug: Invalid mode: 'normal'. Falling back to 'base' mode.

### ISSUE THREAD

**Issue by vaskark** [0xstepit/flow.nvim#19]
### Did you check docs and existing issues?

- [X] I have read all the flow.nvim docs
- [X] I have searched the existing issues of flow.nvim

### Neovim version (nvim -v)

0.10.3

### Operating system/version

Ubuntu 24.10.1

### Describe the bug

Transparency not working.

### Steps To Reproduce

My config:

```
return {
  "0xstepit/flow.nvim",
  lazy = false,
  priority = 1000,
  tag = "v1.0.0",
  opts = {
    theme = {
      style = "dark", --  "dark" | "light"
      contrast = "default", -- "default" | "high"
      transparent = true, -- true | false
    },
    colors = {
      mode = "default", -- "default" | "dark" | "light"
      fluo = "orange", -- "pink" | "cyan" | "yellow" | "orange" | "green"
    },
    ui = {
      borders = "light", -- "theme" | "inverse" | "fluo" | "none"
      aggressive_spell = false, -- true | false
    },
    config = function(_, opts)
      require("flow").setup(opts)
    end,
  },
}
```

### Expected Behavior

Background should be transparent.
It was working before flow updated to v2.0.0.

**Comment by 0xstepit** [comment]
Hey @vaskark! I see you are using the new config of v2 but forcing Lazy to upload the v1. If you update the tag to v2.0.0 everything should work fine :)

**Comment by vaskark** [comment]
Thanks for responding.
Unfortunately changing the tag to v2.0.0 didn't work.

**Comment by vaskark** [comment]
I had to change border from light to fluo (for example). Then it worked.

**Comment by 0xstepit** [comment]
You're right! The "light" version is not available. As you can see it is not listed in the same line of possible options. Thanks for catching it

**Comment by 0xstepit** [comment]
Issue fixed here: https://github.com/0xstepit/flow.nvim/commit/41a7810cdc357c22a723ba46aabc09f0ded8e2de thanks again!
