### ISSUE TITLE
bug: Wiggly lines at rust method and macro calls

### ISSUE THREAD

**Issue by Drazhar** [0xstepit/flow.nvim#3]
### Did you check docs and existing issues?

- [X] I have read all the flow.nvim docs
- [X] I have searched the existing issues of flow.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-387+g158ffd646 -> With Neovide

### Operating system/version

Win 11

### Describe the bug

Hey,
I just tried your colorscheme and really like it! There is just one thing which is kinda distracting IMHO.

## Wiggly lines
If I use Neovide + Rust, many method and macro calls get some wiggly red lines below them.
![image](https://github.com/user-attachments/assets/db7cde53-aed5-499f-86bf-a49874189042)

LSP messages get the straight underline:
![image](https://github.com/user-attachments/assets/8b05c565-97b1-49cb-9d10-eda56f8f37e7)

In Alacritty + NVIM + Rust they just get underlines, which most likely is the expected behavior:
![image](https://github.com/user-attachments/assets/dab6c05f-2690-4a11-a0eb-7265be888304)

Also the LSP messages get the straight underline:
![image](https://github.com/user-attachments/assets/bdecbb45-f27b-492d-aedc-61e0a8c8ef85)

Because my brain is wired to see wiggly lines as spelling or code mistakes, this is kinda distracting.

## Dark blue contrast
Maybe this should be a different issue/suggestion, but the dark blue for function/method names could be a tad brighter for improved readability? The contrast to the background is a bit low, at least without a transparent background.

Best regards

### Steps To Reproduce

1. Install Neovide
2. Use lazy.nvim
3. Add this repo as a plugin

### Expected Behavior

No wiggly lines in Neovide for method and macro calls but for the LSP warnings these would be nice, if not necessary.

### Repro

```Lua
I use lazy.nvim with the colorscheme plugin with the following content of the colorscheme.lua:

return {
  {
    "0xstepit/flow.nvim",
    lazy = false,
    priority = 1000,
    opts = {},
    config = function()
      require("flow").setup({
        transparent = false,
        fluo_color = "pink",
        mode = "normal", -- "bright", "normal", "dim"
        aggressive_spell = false,
      })
    end,
  },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "flow",
    },
  },
}
```

**Comment by 0xstepit** [comment]
Hey @Drazhar, thanks for opening the issue and for the feedback. Do you mind sharing a rust repo in which you have this issue? I tried with some rust project I have but I cannot see all the underline you have.

**Comment by 0xstepit** [comment]
For what concern the blue function name/ function, I usually prefer to have more focus on the inside of a function instead of its name. But this is my personal feeling, maybe I could provide a way to change some nvim group color

**Comment by Drazhar** [comment]
> Hey @Drazhar, thanks for opening the issue and for the feedback. Do you mind sharing a rust repo in which you have this issue? I tried with some rust project I have but I cannot see all the underline you have.

These where just some small tests I did with Bevy. The issue also shows up in a brand new hello world Rust project initialized with `cargo new`:
![image](https://github.com/user-attachments/assets/b0d37a9c-a0bc-4c0b-943e-c567844978b0)

But again, it's only in combination with [Neovide](https://neovide.dev/). NVIM in the Alacritty terminal only shows the underline:
![image](https://github.com/user-attachments/assets/90e11f4a-2b45-4cf6-b377-6a823cf7f333)

For example with the theme *kanagawa*, I don't get any underlines:
![image](https://github.com/user-attachments/assets/39aa6c70-73d0-4784-bafb-44b0f545a91b)


## After some digging

I realized, that only some methods/macros from the bevy and the std library had the wiggly lines and also didn't show any hover information (lazy.nvim default <SHIFT>+K). Methods from my own structs or macros didn't show any lines.

After some more testing, it seems, that the issue is within the [Pixi](https://prefix.dev/) environment I'm using. Inside the `pixi shell`, no definitions from bevy or the std library can be read by the rust-analyzer. But the project can be build and run without any issues.

If I use my global rust installation, I don't have any issues with the rust-analyzer and no lines are shown.


## Conclusion

The issue isn't caused from your color-scheme.
But thanks to the flow theme I spotted an issue with my pixi environment. So an additional thanks for that.

**Comment by Drazhar** [comment]
> For what concern the blue function name/ function, I usually prefer to have more focus on the inside of a function instead of its name. But this is my personal feeling, maybe I could provide a way to change some nvim group color

On my main monitor, the readability of the dark blue color for the functions is way better than on the go on my laptop screen. So this also isn't really an issue anymore. But an option to change the brightness would still be nice to have.

**Comment by Drazhar** [comment]
I will close this topic, because the main issue is solved ⭐
