### ISSUE TITLE
issue: Error in HEX values on the palette 

### ISSUE THREAD

**Issue by Someone-Who-Writes-Code** [0xstepit/flow.nvim#4]
### Did you check docs and existing issues?

- [X] I have read all the flow.nvim docs
- [X] I have searched the existing issues of flow.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1 - Build Type: Release - LuaJIT 2.1.17

### Operating system/version

Debian 12 bookworm on WSL2 W10

### Describe the bug

I'm working on bringing your colorscheme to [Terminal on Windows](https://github.com/microsoft/terminal) for those who are using Neovim through WSL. While reading the HEX values in your `flow-palette.png` I noticed that the values for `light blue` and `cyan` in the `dim` row are the same. After perusing the repo, I found the HSL values to get the correct HEX:
```

light_blue = {
    dim = "#0F578A"
}

cyan = {
    dim = "#14B8AA"
}
```

### Steps To Reproduce

`flow-palette.png` -> `dim` row -> `light blue` and `cyan`

### Expected Behavior

I do not know how to create that kind of picture to represent the palette, but, if I find a way I'll submit the corrected .png.

**Comment by 0xstepit** [comment]
Hey @Someone-Who-Writes-Code thanks for opening this issue! I created the image with Figma but it is not shared the file. I will update it in the following days :) thanks again!

**Comment by 0xstepit** [comment]
Fixed!

**Comment by Someone-Who-Writes-Code** [comment]
Thank you! I’ve been out for a while due to medical issues, but I wrote a Python program that outputs a similar template in PNG format and totally forgot to put it here. In a couple days I'll send you the colorschemes to windows terminal.
